name : "CI"

on:
  push:
    branches: 
        - main
        - dev

jobs:
    "build":
        runs-on: ubuntu-latest
        steps:
            - name: "Setup Node"
                uses: actions/setup-node@v4
                with:
                    node-version: "20"
            - name: "install the dependencies"
                run: npm install