name : "CI"

on:
  push:
    branches: 
        - main
        - dev

jobs:
    "build":
        runs-on: ubuntu-latest
        steps:
            - name: "Setup Node"
              uses: actions/setup-node@v4
              with:
                node-version: 18
                cache: "npm"
                
            - name: "Checkout code"
              uses: actions/checkout@v3
              
            - name: "Install dependencies"
              run: npm install
              