name : "CI"

on:
  push:
    branches: 
        - main
        - dev

jobs:
    "build":
        runs-on: ubuntu-latest
        steps:
            - name: "Setup Node"
              uses: actions/setup-node@v4
              with:
                node-version: 20
                
            - name: "Checkout code"
              uses: actions/checkout@v3

            - name: "checking the files"
              run: ls -al
              
            - name: "Install dependencies"
              run: npm install
            
            - name: "Build"
              run: npm run build
            
            - name: "Upload artifact"
              uses: actions/upload-artifact@v4
              with:
                name: build
                path: dist
            